# Generated by Django 5.1.5 on 2025-03-07 14:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_state_options_state_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offense',
            options={'ordering': ['-offense_date']},
        ),
        migrations.AlterModelOptions(
            name='trafficlaw',
            options={'ordering': ['law_name']},
        ),
        migrations.RemoveField(
            model_name='trafficlaw',
            name='description',
        ),
        migrations.AddField(
            model_name='offense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trafficlaw',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trafficlaw',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='offense',
            name='law',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offenses', to='core.trafficlaw'),
        ),
        migrations.AlterField(
            model_name='offense',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.state'),
        ),
        migrations.AlterField(
            model_name='offense',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], db_index=True, default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='trafficlaw',
            name='law_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='offense',
            index=models.Index(fields=['status'], name='core_offens_status_6640fd_idx'),
        ),
        migrations.AddIndex(
            model_name='offense',
            index=models.Index(fields=['state'], name='core_offens_state_i_355fa6_idx'),
        ),
    ]
